# Generated by Django 5.0.2 on 2024-09-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_feed_generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('price_percentage_factor', models.FloatField(blank=True, max_length=65535, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='group_tags',
            field=models.ManyToManyField(to='product_feed_generator.grouptag'),
        ),
    ]
