# Generated by Django 5.0.2 on 2024-09-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_feed_generator', '0002_grouptag_product_group_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouptag',
            name='name',
            field=models.CharField(max_length=127, unique=True),
        ),
    ]
